/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardDisplayDialog: typeof import('./src/components/arena/CardDisplayDialog.vue')['default']
    CardName: typeof import('./src/components/common/CardName.vue')['default']
    CardNameList: typeof import('./src/components/common/CardNameList.vue')['default']
    CloneButton: typeof import('./src/components/decks/CloneButton.vue')['default']
    CopyJsonButton: typeof import('./src/components/builder/CopyJsonButton.vue')['default']
    CountDisplay: typeof import('./src/components/common/CountDisplay.vue')['default']
    DeckBuilder: typeof import('./src/components/builder/DeckBuilder.vue')['default']
    DeckCard: typeof import('./src/components/decks/DeckCard.vue')['default']
    DeckDisplay: typeof import('./src/components/builder/DeckDisplay.vue')['default']
    DeckDisplayDialog: typeof import('./src/components/decks/DeckDisplayDialog.vue')['default']
    DeleteButton: typeof import('./src/components/decks/DeleteButton.vue')['default']
    EditButton: typeof import('./src/components/decks/EditButton.vue')['default']
    EnergyIcon: typeof import('./src/components/common/EnergyIcon.vue')['default']
    EnergySelector: typeof import('./src/components/builder/EnergySelector.vue')['default']
    EnergyZone: typeof import('./src/components/arena/EnergyZone.vue')['default']
    GameLog: typeof import('./src/components/arena/GameLog.vue')['default']
    HpChange: typeof import('./src/components/arena/HpChange.vue')['default']
    InPlayCardSlot: typeof import('./src/components/arena/InPlayCardSlot.vue')['default']
    PlayerDeck: typeof import('./src/components/arena/PlayerDeck.vue')['default']
    PlayerDiscard: typeof import('./src/components/arena/PlayerDiscard.vue')['default']
    PlayerHandHidden: typeof import('./src/components/arena/PlayerHandHidden.vue')['default']
    PlayerHandVisible: typeof import('./src/components/arena/PlayerHandVisible.vue')['default']
    PlayerInfo: typeof import('./src/components/arena/PlayerInfo.vue')['default']
    PlayerPokemon: typeof import('./src/components/arena/PlayerPokemon.vue')['default']
    PlayingCard: typeof import('./src/components/common/PlayingCard.vue')['default']
    PlayingCardImage: typeof import('./src/components/common/PlayingCardImage.vue')['default']
    PlayingField: typeof import('./src/components/arena/PlayingField.vue')['default']
    PokemonDescriptor: typeof import('./src/components/arena/PokemonDescriptor.vue')['default']
    ResetDeckButton: typeof import('./src/components/builder/ResetDeckButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./src/components/builder/SearchPanel.vue')['default']
    SelectableCard: typeof import('./src/components/builder/SelectableCard.vue')['default']
    TooltipButton: typeof import('./src/components/common/TooltipButton.vue')['default']
  }
}
