/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InPlayPokemonCard: typeof import('./src/components/InPlayPokemonCard.vue')['default']
    PlayingCard: typeof import('./src/components/PlayingCard.vue')['default']
    PlayingField: typeof import('./src/components/PlayingField.vue')['default']
  }
}
