export const allExpansions = {
  "PROMO-A": "Promo A",
  A1: "Genetic Apex",
  A1a: "Mythical Island",
  A2: "Space-Time Smackdown",
  A2a: "Triumphant Light",
  A2b: "Shining Revelry",
  A3: "Celestial Guardians",
  A3a: "Extradimensional Crisis",
  A3b: "Eevee Grove",
  A4: "Wisdom of Sea and Sky",
  A4a: "Secluded Springs",
  A4b: "Deluxe Pack: ex",
  "PROMO-B": "Promo B",
  B1: "Mega Rising",
  B1a: "Crimson Blaze",
  B2: "Fantastical Parade",
  B2a: "Paldean Wonders",
  B2b: "Mega Shine",
  B3: "Pulsing Aura",
  B3a: "Paradox Drive",
  B3b: "Everyday Wonders",
  B4: "Ruler of the Skies",
  B4a: "Team Rocket’s Ambition",
  B4b: "Deluxe Pack: Mega",
};
